### ISSUE TITLE
Reading for Shaya

### ISSUE THREAD

**Issue by medvidov** [medvidov/IMaSC#51]
- [Virtual Environments](https://docs.python.org/3/library/venv.html)

- [Jupyter Notebooks](https://jupyter.org/)

**Comment by medvidov** [comment]
Read about our metrics: precision, recall, F-Score, accuracy

**Comment by vc1492a** [comment]
Eventually, we could also look at `coverage`!

**Comment by medvidov** [comment]
> Eventually, we could also look at `coverage`!

Hell, ~I~ need to read about that.
