### ISSUE TITLE
Make a cute little API

### ISSUE THREAD

**Issue by shayanaimi** [medvidov/IMaSC#58]
Goal: user uploads a PDF, program processes it into natural language, run the model on it, spit out entities and their labels

Starting point: using [this article](https://stackabuse.com/python-for-nlp-working-with-text-and-pdf-files/) which talks about [PyPDF2](https://pythonhosted.org/PyPDF2/)

Maybe additional feature would be you can submit your own annotations of the data to help improve the model and have it also spit out metrics?

**Comment by vc1492a** [comment]
API should:

- load the trained spacy model
- have a single endpoint that:
  - takes in a string value 
  - returns a JSON dictionary with a list of instruments and missions identified 
- for the PDF processing
  - take a look at PFF Miner as that is what we used for processing the PDFs originally into natural language for training
  - can also use Apache Tika as it has several PDF parsers
  - use the text cleaning code we already have after parsing the PDFs before feeding into spacy and hitting the rest api 

The rest API is a means to an end 😄 

I wouldn't worry about annotations.

**Comment by shayanaimi** [comment]
api_stuff folder in the repo holds api.py, which you can run and then access localhost/5000 on your browser. The user submits text, and the API spits out a table of each entity it recognized plus its label and how confident it is in that label. I don't know if this is proper git flow but I'm going to close this and create a new gentle issue for hopeful PDF processing in the future.
