### ISSUE TITLE
Plot that shows how performance is impacted by the number of observations in the training data

### ISSUE THREAD

**Issue by vc1492a** [medvidov/IMaSC#63]
This would be good to see and is good documentation to back up the question "why do you spend time annotating?" 

See matplotlib and/or seaborn or plotly.

**Comment by shayanaimi** [comment]
performance_vs_training.py trains the model on increasing numbers of annotations and then tests it and generates a dict with all of that data. I'm going to close this issue but will create a new one for some future things I want to see happen in this area

**Comment by shayanaimi** [comment]
performance_vs_training.py trains the model on increasing numbers of annotations and then tests it and generates a dict with all of that data. I'm going to close this issue but will create a new one for some future things I want to see happen in this area
